package ch.zhaw.it.pm4.javer.compiler.parser;

import ch.zhaw.it.pm4.javer.compiler.annotation.JacocoGenerated;
import ch.zhaw.it.pm4.javer.compiler.ast.nodes.CompilationUnit;
import ch.zhaw.it.pm4.javer.compiler.ast.nodes.caseLabel.CaseLabelAstNode;
import ch.zhaw.it.pm4.javer.compiler.ast.nodes.caseLabel.EnumCaseLabel;
import ch.zhaw.it.pm4.javer.compiler.ast.nodes.caseLabel.LiteralCaseLabel;
import ch.zhaw.it.pm4.javer.compiler.ast.nodes.declaration.*;
import ch.zhaw.it.pm4.javer.compiler.ast.nodes.statement.*;
import ch.zhaw.it.pm4.javer.compiler.ast.nodes.type.*;
import ch.zhaw.it.pm4.javer.compiler.lexer.Token;
import ch.zhaw.it.pm4.javer.compiler.lexer.TokenType;
import ch.zhaw.it.pm4.javer.compiler.misc.SourceLocation;
import ch.zhaw.it.pm4.javer.compiler.misc.diagnostics.DiagnosticBag;
import ch.zhaw.it.pm4.javer.compiler.misc.diagnostics.Severity;
import ch.zhaw.it.pm4.misc.JaverLogger;

import java.util.ArrayList;
import java.util.List;

/**
 * A Recursive Descent Parser for the Javer programming language.
 * <p>
 * This parser is responsible for taking a linear sequence of {@link Token}s
 * generated by the Lexer and organizing them into a Concrete Syntax Tree (CST).
 * It strictly follows the LL(1) Javer formal grammar.
 * <p>
 * To support the educational goals of the language, this parser implements
 * graceful error recovery. Instead of throwing exceptions upon encountering
 * syntax errors, it records them in the {@link DiagnosticBag} and attempts
 * to continue parsing to find subsequent errors.
 */
@JacocoGenerated("Skeleton only, remove when fully implemented")
public class Parser {

    private final List<Token> tokens;
    private final DiagnosticBag diagnosticBag;
    private int currentPosition = 0;

    private final TokenType[] tokenTypesTypeHead = {
            TokenType.TYPE_INTEGER, TokenType.TYPE_DOUBLE,
            TokenType.TYPE_BOOLEAN, TokenType.TYPE_STRING, TokenType.TYPE_CHARACTER,
            TokenType.TYPE_STRUCT, TokenType.TYPE_ENUM
    };

    private final TokenType[] tokenTypePrimitiveTypes = {
            TokenType.TYPE_INTEGER,
            TokenType.TYPE_DOUBLE,
            TokenType.TYPE_BOOLEAN,
            TokenType.TYPE_STRING,
            TokenType.TYPE_CHARACTER
    };

    /**
     * Constructs a new Parser instance.
     *
     * @param diagnosticBag The diagnostic bag to which syntax errors will be reported.
     * @param tokens        The complete list of tokens generated by the Lexer.
     *                      Must end with an EOF (End of File) token.
     *                      errors gracefully without halting the compiler pipeline.
     */
    public Parser(List<Token> tokens, DiagnosticBag diagnosticBag) {
        this.tokens = tokens;
        this.diagnosticBag = diagnosticBag;
    }

    /**
     * Starts the parsing process.
     * <p>
     * This method acts as the entry point for the compiler pipeline and matches
     * the root {@code compilationUnit} grammar rule. It iterates through the
     * token stream and constructs an abstract syntax tree.
     *
     * @return The root node ({@link CompilationUnit}) of the resulting
     * Abstract Syntax Tree (AST).
     */
    public CompilationUnit parse() {
        return parseCompilationUnit();
    }

    /**
     * @return The current token in the token stream without consuming it.
     */
    private Token currentToken() {
        return peek(0);
    }

    /**
     * @return The next token in the token stream (lookahead = 1) without consuming it.
     */
    private Token lookahead() {
        return peek(1);
    }

    /**
     * @param offset The number of tokens to look ahead (only positive)
     * @return The token at the specified offset from the current position.
     * if the resulting index exceeds the bounds of the token list, it returns the last token (EOF).
     */
    private Token peek(int offset) {
        int i = currentPosition + offset;
        if (i < 0) i = 0;
        return i >= tokens.size() ? tokens.getLast() : tokens.get(i);
    }

    /**
     * @param tokenType The token type to match against the current token.
     * @return true if the current token matches the specified token type, false otherwise.
     */
    private boolean matchCurrentToken(TokenType tokenType) {
        return currentToken().getTokenType() == tokenType;
    }

    /**
     * @param token     the token to be matched against
     * @param tokenType the tokentype to match
     * @return true if the type of token matches with the given tokentype, false otherwise
     */
    private boolean matchToken(Token token, TokenType tokenType) {
        return token.getTokenType() == tokenType;
    }

    /**
     * @param token      the token to be matched against
     * @param tokenTypes the tokentypes to match
     * @return true if the type of token matches with one of the given tokentypes, false otherwise (no match at all)
     */
    private boolean matchTokens(Token token, List<TokenType> tokenTypes) {
        for (TokenType tokenType : tokenTypes) {
            if (matchToken(token, tokenType)) return true;
        }
        return false;
    }

    /**
     * @param tokenType The token type to match against the next token (lookahead = 1).
     * @return true if the next token matches the specified token type, false otherwise.
     */
    private boolean matchNextToken(TokenType tokenType) {
        return lookahead().getTokenType() == tokenType;
    }

    /**
     * @param tokenTypes The token types to match against the current token.
     * @return true if the current token matches any of the specified token types, false otherwise
     */
    private boolean matchAnyCurrentToken(List<TokenType> tokenTypes) {
        for (TokenType tokenType : tokenTypes) {
            if (matchCurrentToken(tokenType)) return true;
        }
        return false;
    }

    /**
     * @param tokenTypes The token types to match against the next token (lookahead = 1).
     * @return true if the next token matches any of the specified token types, false otherwise
     */
    private boolean matchAnyNextToken(List<TokenType> tokenTypes) {
        TokenType lookAheadTokenType = lookahead().getTokenType();
        for (TokenType tokenType : tokenTypes) {
            if (lookAheadTokenType == tokenType) return true;
        }
        return false;
    }

    /**
     * Consumes the current token and advances the current position to the next token in the stream.
     */
    private void consumeToken() {
        if (currentPosition < tokens.size()) currentPosition++;
    }

    /**
     * @param tokenType The token type that is expected at the current position.
     * @return The current token if it matches the expected token type.
     * If it does not match, a syntax error is reported and a dummy token of the expected type is returned to allow the parser to continue parsing.
     * In either case, the current token is consumed and the parser advances to the next token in the stream.
     */
    private Token expectTokenType(TokenType tokenType) {
        Token token = currentToken();
        if (token.getTokenType() != tokenType) {
            reportExpectedToken(tokenType);
            token = new Token(tokenType, tokenType.toString(), currentToken().getPosition());
        }
        consumeToken();
        return token;
    }

    /**
     * @param tokenTypes The token types that are expected at the current position.
     * @return The current token if it matches any of the expected token type.
     * If it does not match, a syntax error is reported and a dummy token of the expected type (the first of the list) is returned to allow the parser to continue parsing.
     * In either case, the current token is consumed and the parser advances to the next token in the stream.
     */
    private Token expectTokenTypes(List<TokenType> tokenTypes) {
        Token token = currentToken();
        boolean found = false;
        for (TokenType tokenType : tokenTypes) {
            if (token.getTokenType() == tokenType) {
                found = true;
                break;
            }
        }
        if (!found) {
            reportExpectedTokens(tokenTypes);
            TokenType tempTokenType = tokenTypes.getFirst();
            token = new Token(tempTokenType, tempTokenType.toString(), currentToken().getPosition());
        }
        consumeToken();
        return token;
    }

    /**
     * @param tokenType The token type that was expected but not found at the current position.
     *                  This method creates a syntax error diagnostic indicating that the expected token type was not found.
     */
    private void reportExpectedToken(TokenType tokenType) {
        Token current = currentToken();
        SourceLocation location = current.getPosition();
        String message = String.format(
                "Expected token %s but found %s.",
                tokenType,
                current.getTokenType()
        );
        JaverLogger.error(message);
        diagnosticBag.add(location, Severity.ERROR, message);
    }

    /**
     * @param tokenTypes The token types that were expected but not found at the current position.
     *                   This method creates a syntax error diagnostic indicating that none of the expected token types were found.
     */
    private void reportExpectedTokens(List<TokenType> tokenTypes) {
        Token current = currentToken();
        SourceLocation location = current.getPosition();
        StringBuilder expected = new StringBuilder();
        for (TokenType tokenType : tokenTypes) {
            expected.append(tokenType)
                    .append(", ");
        }
        if (expected.toString().endsWith(", ")) {
            expected.delete(expected.length() - 2, expected.length());
        }
        String message = String.format(
                "Expected token %s but found %s.",
                expected,
                current.getTokenType()
        );
        JaverLogger.error(message);
        diagnosticBag.add(location, Severity.ERROR, message);
    }

    private void synchronizeUntilFound(List<TokenType> tokenTypes) {
        while (!matchAnyCurrentToken(tokenTypes) && !matchCurrentToken(TokenType.SPECIAL_END_OF_FILE)) {
            consumeToken();
        }
    }

    // ============================================================
    // Top-Level
    // ============================================================

    private CompilationUnit parseCompilationUnit() {
        List<TokenType> firstDeclarationTokens = List.of(
                TokenType.TYPE_ENUM,
                TokenType.TYPE_STRUCT,
                TokenType.KEYWORD_FUNCTION);
        List<DeclarationAstNode> declarations = new ArrayList<>();
        while (!matchCurrentToken(TokenType.SPECIAL_END_OF_FILE)) {
            if (matchAnyCurrentToken(firstDeclarationTokens)) {
                declarations.add(parseDeclaration());
            } else {
                reportExpectedTokens(firstDeclarationTokens);
                synchronizeUntilFound(firstDeclarationTokens);
            }
        }
        return new CompilationUnit(declarations);
    }

    private DeclarationAstNode parseDeclaration() {
        if (matchCurrentToken(TokenType.TYPE_ENUM)) return parseEnumDeclaration();
        if (matchCurrentToken(TokenType.KEYWORD_FUNCTION)) return parseFunctionDeclaration();
        return parseStructDeclaration();
    }

    private EnumDeclaration parseEnumDeclaration() {
        return new EnumDeclaration("dummy", new ArrayList<>());
    }

    private EnumItem parseEnumItem() {
        return EnumItem
                .builder("dummy")
                .value(1)
                .build();
    }

    private StructDeclaration parseStructDeclaration() {
        return new StructDeclaration("dummy", new ArrayList<>());
    }

    private StructField parseStructField() {
        return new StructField(new PrimitiveType(PrimitiveTypeKind.BOOL), "dummy");
    }

    private FunctionDeclaration parseFunctionDeclaration() {
        expectTokenType(TokenType.KEYWORD_FUNCTION);
        TypeAstNode returnType = parseReturnType();
        String functionName = expectTokenType(TokenType.ID_IDENTIFIER).getValue();
        expectTokenType(TokenType.SYMBOL_LEFT_PARENTHESIS);
        List<FunctionParameter> functionParameters = parseFunctionParameters();
        expectTokenType(TokenType.SYMBOL_RIGHT_PARENTHESIS);
        BlockStatement block = parseBlock();
        return new FunctionDeclaration(returnType, functionName, functionParameters, block);
    }

    private FunctionParameter parseFunctionParameter() {
        TypeAstNode type = parseType();
        String parameterName = expectTokenType(TokenType.ID_IDENTIFIER).getValue();
        return new FunctionParameter(parameterName, type);
    }

    // ============================================================
    // Types
    // ============================================================

    private TypeAstNode parseType() {
        TypeAstNode baseType = parseTypeHead();
        if (matchCurrentToken(TokenType.SYMBOL_LEFT_BRACKET)) return wrapArrayDimensions(baseType);
        return baseType;
    }

    private TypeAstNode parseReturnType() {
        if (matchAnyCurrentToken(List.of(tokenTypesTypeHead))) return parseTypeHead();
        return parseVoidType();
    }

    private TypeAstNode parseTypeHead() {
        if (matchAnyCurrentToken(List.of(tokenTypePrimitiveTypes))) return parsePrimitiveType();
        return parseNamedType();
    }

    private PrimitiveType parsePrimitiveType() {
        Token token = expectTokenTypes(List.of(tokenTypePrimitiveTypes));
        return new PrimitiveType(toPrimitiveTypeKind(token));
    }

    private NamedType parseNamedType() {
        Token typeToken = expectTokenTypes(List.of(TokenType.TYPE_STRUCT, TokenType.TYPE_ENUM));
        Token nameToken = expectTokenType(TokenType.ID_IDENTIFIER);
        return new NamedType(toNameTypeKind(typeToken), nameToken.getValue());
    }

    private VoidType parseVoidType() {
        expectTokenType(TokenType.TYPE_VOID);
        return new VoidType();
    }

    private TypeAstNode wrapArrayDimensions(TypeAstNode baseType) {
        TypeAstNode wrappedType = baseType;
        while (matchCurrentToken(TokenType.SYMBOL_LEFT_BRACKET)) {
            expectTokenType(TokenType.SYMBOL_LEFT_BRACKET);
            expectTokenType(TokenType.SYMBOL_RIGHT_BRACKET);
            wrappedType = new ArrayType(wrappedType);
        }
        return wrappedType;
    }

    // ============================================================
    // Statements / Blocks
    // ============================================================

    private BlockStatement parseBlock() {
        List<StatementAstNode> statements = new ArrayList<>();
        expectTokenType(TokenType.SYMBOL_LEFT_BRACE);
        while (!matchCurrentToken(TokenType.SYMBOL_RIGHT_BRACE)) {
            statements.add(parseStatement());
        }
        expectTokenType(TokenType.SYMBOL_RIGHT_BRACE);
        return new BlockStatement(statements);
    }

    private StatementAstNode parseStatement() {
        return switch (currentToken().getTokenType()) {
            case TokenType.KEYWORD_IF -> parseIfStatement();
            case TokenType.KEYWORD_WHILE -> parseWhileStatement();
            case TokenType.KEYWORD_DO -> parseDoWhileStatement();
            case TokenType.KEYWORD_FOR -> parseForStatement();
            case TokenType.KEYWORD_SWITCH -> parseSwitchStatement();
            case TokenType.KEYWORD_RETURN, TokenType.KEYWORD_BREAK, TokenType.KEYWORD_CONTINUE -> parseJumpStatement();
            case TokenType.KEYWORD_LET -> parseVarDeclarationStatement();
            case TokenType.SYMBOL_LEFT_BRACE -> parseBlock();
            default -> parseExpressionStatement();
        };
    }

    private IfStatement parseIfStatement() {
        return IfStatement
                .builder(new LiteralExpression<>(LiteralKind.INT, 1), parseStatement())
                .elseBranch(parseStatement())
                .build();
    }

    private WhileStatement parseWhileStatement() {
        return new WhileStatement(new LiteralExpression<>(LiteralKind.INT, 1), parseStatement());
    }

    private DoWhileStatement parseDoWhileStatement() {
        return new DoWhileStatement(new LiteralExpression<>(LiteralKind.INT, 1), parseBlock());
    }

    private ForStatement parseForStatement() {
        return ForStatement
                .builder(parseStatement())
                .forInit(parseForInit())
                .condition(new LiteralExpression<>(LiteralKind.INT, 1))
                .update(new ArrayList<>())
                .build();
    }

    private ForInit parseForInit() {
        return parseForInitVarDeclaration();
    }

    private ForInitVarDeclaration parseForInitVarDeclaration() {
        return new ForInitVarDeclaration(VarDeclarationStatement
                .builder(new PrimitiveType(PrimitiveTypeKind.INT), "dummy")
                .build());
    }

    private ForInitExpressionList parseForInitExpressionList() {
        return new ForInitExpressionList(new ArrayList<>());
    }

    private SwitchStatement parseSwitchStatement() {
        return new SwitchStatement(new LiteralExpression<>(LiteralKind.INT, 1), new ArrayList<>());
    }

    private SwitchCase parseSwitchCase() {
        return new SwitchCase(false, new ArrayList<>(), parseStatement());
    }

    private StatementAstNode parseJumpStatement() {
        if (matchCurrentToken(TokenType.KEYWORD_RETURN)) return parseReturnStatement();
        if (matchCurrentToken(TokenType.KEYWORD_BREAK)) return parseBreakStatement();
        return parseContinueStatement();
    }

    private BreakStatement parseBreakStatement() {
        expectTokenType(TokenType.KEYWORD_BREAK);
        return new BreakStatement();
    }

    private ContinueStatement parseContinueStatement() {
        expectTokenType(TokenType.KEYWORD_CONTINUE);
        return new ContinueStatement();
    }

    private ReturnStatement parseReturnStatement() {
        expectTokenType(TokenType.KEYWORD_RETURN);
        if (matchCurrentToken(TokenType.SYMBOL_SEMICOLON)) {
            expectTokenType(TokenType.SYMBOL_SEMICOLON);
            return ReturnStatement
                    .builder()
                    .build();
        }
        ExpressionAstNode expression = parseExpression();
        expectTokenType(TokenType.SYMBOL_SEMICOLON);
        return ReturnStatement
                .builder(expression)
                .build();
    }

    private VarDeclarationStatement parseVarDeclarationStatement() {
        return VarDeclarationStatement.builder(new PrimitiveType(PrimitiveTypeKind.INT), "dummy").build();
    }

    private StatementAstNode parseExpressionStatement() {
        return parseExpression();
    }

    // ============================================================
    // Switch / Case Labels
    // ============================================================

    private LiteralCaseLabel parseLiteralCaseLabel() {
        return new LiteralCaseLabel(new LiteralExpression<>(LiteralKind.INT, 1));
    }

    private EnumCaseLabel parseEnumCaseLabel() {
        return new EnumCaseLabel("dummy", "dummy");
    }

    // ============================================================
    // Variable / Array Initializers
    // ============================================================

    private ArrayInitExpression parseArrayInitExpression() {
        return new ArrayInitExpression(new ArrayList<>());
    }

    private ExpressionAstNode parseVarInitializer() {
        return new LiteralExpression<>(LiteralKind.INT, 1);
    }

    // ============================================================
    // Expression Lists
    // ============================================================

    private List<ExpressionAstNode> parseExpressionList() {
        return new ArrayList<>();
    }

    private List<ExpressionAstNode> parseOptionalExpressionList() {
        return new ArrayList<>();
    }

    // ============================================================
    // Expressions
    // ============================================================

    private ExpressionAstNode parseExpression() {
        return parseAssignment();
    }

    private ExpressionAstNode parseAssignment() {
        return parseConditional();
    }

    private AssignOperator parseAssignOperator() {
        return toAssignOperator(currentToken());
    }

    private ExpressionAstNode parseConditional() {
        return parseLogicalOr();
    }

    private ExpressionAstNode parseLogicalOr() {
        return parseLogicalAnd();
    }

    private ExpressionAstNode parseLogicalAnd() {
        return parseInclusiveOr();
    }

    private ExpressionAstNode parseInclusiveOr() {
        return parseExclusiveOr();
    }

    private ExpressionAstNode parseExclusiveOr() {
        return parseAndExpression();
    }

    private ExpressionAstNode parseAndExpression() {
        return parseEqualityExpression();
    }

    private ExpressionAstNode parseEqualityExpression() {
        return parseRelationalExpression();
    }

    private ExpressionAstNode parseRelationalExpression() {
        return parseShiftExpression();
    }

    private ExpressionAstNode parseShiftExpression() {
        return parseAdditiveExpression();
    }

    private ExpressionAstNode parseAdditiveExpression() {
        return parseMultiplicativeExpression();
    }

    private ExpressionAstNode parseMultiplicativeExpression() {
        return parseUnaryExpression();
    }

    private ExpressionAstNode parseUnaryExpression() {
        return parsePostfixExpression();
    }

    private ExpressionAstNode parsePostfixExpression() {
        return parsePrimaryExpression();
    }

    private ExpressionAstNode parsePrimaryExpression() {
        return new LiteralExpression<>(LiteralKind.INT, 1);
    }

    // ============================================================
    // Postfix / Access / Call / New
    // ============================================================

    private ExpressionAstNode parseCallExpression() {
        return new CallExpression("dummy", new ArrayList<>());
    }

    private ExpressionAstNode parseNameExpression() {
        return new NameExpression("dummy");
    }

    private IndexExpression parseIndexExpression(ExpressionAstNode target) {
        return new IndexExpression(target, new LiteralExpression<>(LiteralKind.INT, 1));
    }

    private MemberAccessExpression parseMemberAccessExpression(ExpressionAstNode target) {
        return new MemberAccessExpression(target, "dummy");
    }

    private NewExpression parseNewExpression() {
        return NewExpression.builder(new PrimitiveType(PrimitiveTypeKind.INT)).build();
    }

    private List<ExpressionAstNode> parseNewArrayDimensions() {
        return new ArrayList<>();
    }

    // ============================================================
    // Literals
    // ============================================================

    private LiteralExpression<?> parseLiteralExpression() {
        return new LiteralExpression<>(LiteralKind.INT, 1);
    }

    private LiteralExpression<?> parseNumberLiteral() {
        return parseLiteralExpression();
    }

    private LiteralExpression<Boolean> parseBooleanLiteral() {
        return new LiteralExpression<>(LiteralKind.BOOLEAN, true);
    }

    private LiteralExpression<String> parseStringLiteral() {
        return new LiteralExpression<>(LiteralKind.STRING, "dummy");
    }

    private LiteralExpression<Character> parseCharLiteral() {
        return new LiteralExpression<>(LiteralKind.CHAR, 'a');
    }

    private LiteralExpression<Void> parseNullLiteral() {
        return new LiteralExpression<>(LiteralKind.NULL, null);
    }

    // ============================================================
    // Operator Mapping Helpers
    // ============================================================

    private BinaryExpressionKind toBinaryExpressionKind(Token token) {
        return switch (token.getTokenType()) {
            case TokenType.OPERATOR_PLUS -> BinaryExpressionKind.ADD;
            case TokenType.OPERATOR_MINUS -> BinaryExpressionKind.SUBTRACT;
            case TokenType.OPERATOR_MULTIPLY -> BinaryExpressionKind.MULTIPLY;
            case TokenType.OPERATOR_DIVIDE -> BinaryExpressionKind.DIVIDE;
            case TokenType.OPERATOR_MODULO -> BinaryExpressionKind.MODULO;
            case TokenType.OPERATOR_AND -> BinaryExpressionKind.AND;
            case TokenType.OPERATOR_OR -> BinaryExpressionKind.OR;
            case TokenType.OPERATOR_BITWISE_OR -> BinaryExpressionKind.BITWISE_OR;
            case TokenType.OPERATOR_BITWISE_AND -> BinaryExpressionKind.BITWISE_AND;
            case TokenType.OPERATOR_BITWISE_XOR -> BinaryExpressionKind.BITWISE_XOR;
            case TokenType.OPERATOR_EQUALS -> BinaryExpressionKind.EQUALS;
            case TokenType.OPERATOR_NOT_EQUALS -> BinaryExpressionKind.NOT_EQUALS;
            case TokenType.OPERATOR_LESS_THAN -> BinaryExpressionKind.LESS;
            case TokenType.OPERATOR_LESS_EQUAL -> BinaryExpressionKind.LESS_EQUALS;
            case TokenType.OPERATOR_GREATER_THAN -> BinaryExpressionKind.GREATER;
            case TokenType.OPERATOR_GREATER_EQUAL -> BinaryExpressionKind.GREATER_EQUALS;
            case TokenType.OPERATOR_BITSHIFT_LEFT -> BinaryExpressionKind.SHIFT_LEFT;
            case TokenType.OPERATOR_BITSHIFT_RIGHT -> BinaryExpressionKind.SHIFT_RIGHT;
            default -> BinaryExpressionKind.INVALID;
        };
    }

    private UnaryExpressionKind toUnaryExpressionKind(Token token) {
        return switch (token.getTokenType()) {
            case TokenType.OPERATOR_PLUS -> UnaryExpressionKind.PLUS;
            case TokenType.OPERATOR_MINUS -> UnaryExpressionKind.MINUS;
            case TokenType.OPERATOR_LOGICAL_NOT -> UnaryExpressionKind.LOGICAL_NOT;
            case TokenType.OPERATOR_BITWISE_NOT -> UnaryExpressionKind.BITWISE_NOT;
            case TokenType.OPERATOR_INCREMENT -> UnaryExpressionKind.PRE_INCREMENT;
            case TokenType.OPERATOR_DECREMENT -> UnaryExpressionKind.PRE_DECREMENT;
            default -> UnaryExpressionKind.INVALID;
        };
    }

    private PostfixOperationKind toPostfixOperationKind(Token token) {
        return switch (token.getTokenType()) {
            case TokenType.OPERATOR_INCREMENT -> PostfixOperationKind.INCREMENT;
            case TokenType.OPERATOR_DECREMENT -> PostfixOperationKind.DECREMENT;
            default -> PostfixOperationKind.INVALID;
        };
    }

    private AssignOperator toAssignOperator(Token token) {
        return switch (token.getTokenType()) {
            case TokenType.OPERATOR_ASSIGN -> AssignOperator.ASSIGN;
            case TokenType.OPERATOR_PLUS_ASSIGN -> AssignOperator.ADD_ASSIGN;
            case TokenType.OPERATOR_MINUS_ASSIGN -> AssignOperator.SUB_ASSIGN;
            case TokenType.OPERATOR_MULTIPLY_ASSIGN -> AssignOperator.MUL_ASSIGN;
            case TokenType.OPERATOR_DIVIDE_ASSIGN -> AssignOperator.DIV_ASSIGN;
            case TokenType.OPERATOR_MODULO_ASSIGN -> AssignOperator.MOD_ASSIGN;
            case TokenType.OPERATOR_BITWISE_OR_ASSIGN -> AssignOperator.BITWISE_OR_ASSIGN;
            case TokenType.OPERATOR_BITWISE_AND_ASSIGN -> AssignOperator.BITWISE_AND_ASSIGN;
            case TokenType.OPERATOR_BITWISE_XOR_ASSIGN -> AssignOperator.BITWISE_XOR_ASSIGN;
            case TokenType.OPERATOR_BITSHIFT_LEFT_ASSIGN -> AssignOperator.LEFT_SHIFT_ASSIGN;
            case TokenType.OPERATOR_BITSHIFT_RIGHT_ASSIGN -> AssignOperator.RIGHT_SHIFT_ASSIGN;
            default -> AssignOperator.INVALID;
        };
    }

    private PrimitiveTypeKind toPrimitiveTypeKind(Token token) {
        return switch (token.getTokenType()) {
            case TokenType.TYPE_INTEGER -> PrimitiveTypeKind.INT;
            case TokenType.TYPE_DOUBLE -> PrimitiveTypeKind.DOUBLE;
            case TokenType.TYPE_BOOLEAN -> PrimitiveTypeKind.BOOL;
            case TokenType.TYPE_STRING -> PrimitiveTypeKind.STRING;
            case TokenType.TYPE_CHARACTER -> PrimitiveTypeKind.CHAR;
            default -> PrimitiveTypeKind.INVALID;
        };
    }

    private NameTypeKind toNameTypeKind(Token token) {
        return switch (token.getTokenType()) {
            case TokenType.TYPE_STRUCT -> NameTypeKind.STRUCT;
            case TokenType.TYPE_ENUM -> NameTypeKind.ENUM;
            default -> NameTypeKind.INVALID;
        };
    }

    // ============================================================
    // Optional / Repetition Helpers
    // ============================================================

    private List<EnumItem> parseEnumItems() {
        return new ArrayList<>();
    }

    private List<StructField> parseStructFields() {
        return new ArrayList<>();
    }

    private List<FunctionParameter> parseFunctionParameters() {
        List<FunctionParameter> functionParameters = new ArrayList<>();
        if (!matchCurrentToken(TokenType.SYMBOL_RIGHT_PARENTHESIS)) {
            functionParameters.add(parseFunctionParameter());
            while (matchCurrentToken(TokenType.SYMBOL_COMMA)) {
                expectTokenType(TokenType.SYMBOL_COMMA);
                functionParameters.add(parseFunctionParameter());
            }
        }
        return functionParameters;
    }

    private List<SwitchCase> parseSwitchCases() {
        return new ArrayList<>();
    }

    private List<CaseLabelAstNode> parseCaseLabels() {
        return new ArrayList<>();
    }

}
