package ch.zhaw.it.pm4.javer.compiler.lexer;

/**
 * Enum representing different types of tokens.
 */
public enum TokenType {
    // Literals
    LITERAL_INTEGER,
    LITERAL_DOUBLE,
    LITERAL_HEX,
    LITERAL_BINARY,
    LITERAL_OCTAL,
    LITERAL_STRING,
    LITERAL_CHAR,
    LITERAL_BOOLEAN,
    LITERAL_NULL,

    // Identifiers
    ID_IDENTIFIER,

    
    // Keywords
    KEYWORD_IF,
    KEYWORD_ELSE,
    KEYWORD_WHILE,
    KEYWORD_DO,
    KEYWORD_FOR,
    KEYWORD_RETURN,
    KEYWORD_FN,
    KEYWORD_BREAK,
    KEYWORD_CONTINUE,
    KEYWORD_SWITCH,
    KEYWORD_CASE,
    KEYWORD_DEFAULT,
    KEYWORD_LET,
    KEYWORD_CALL,

    //Types and Return types
    TYPE_STRUCT,
    TYPE_INTEGER,
    TYPE_DOUBLE,
    TYPE_BOOLEAN,
    TYPE_STRING,
    TYPE_CHARACTER,
    TYPE_VOID,
    TYPE_ENUM,


    // Operators
    OPERATOR_PLUS,
    OPERATOR_MINUS,
    OPERATOR_MULTIPLY,
    OPERATOR_DIVIDE,
    OPERATOR_MODULO,
    OPERATOR_ASSIGN,
    OPERATOR_PLUS_ASSIGN,
    OPERATOR_MINUS_ASSIGN,
    OPERATOR_MULTIPLY_ASSIGN,
    OPERATOR_DIVIDE_ASSIGN,
    OPERATOR_MODULO_ASSIGN,
    OPERATOR_EQUALS,
    OPERATOR_NOT_EQUALS,
    OPERATOR_LESS_THAN,
    OPERATOR_GREATER_THAN,
    OPERATOR_LESS_EQUAL,
    OPERATOR_GREATER_EQUAL,
    OPERATOR_LOGICAL_NOT,
    OPERATOR_INCREMENT,
    OPERATOR_DECREMENT,
    OPERATOR_OR,
    OPERATOR_AND,
    OPERATOR_BITWISE_AND,
    OPERATOR_BITWISE_OR,
    OPERATOR_BITWISE_XOR,
    OPERATOR_BITWISE_NOT,
    OPERATOR_BITSHIFT_LEFT,
    OPERATOR_BITSHIFT_RIGHT,
    OPERATOR_BITWISE_OR_ASSIGN,
    OPERATOR_BITWISE_AND_ASSIGN,
    OPERATOR_BITWISE_XOR_ASSIGN,
    OPERATOR_BITSHIFT_LEFT_ASSIGN,
    OPERATOR_BITSHIFT_RIGHT_ASSIGN,
    
    // Delimiters
    SYMBOL_LEFT_PARENTHESIS,      // (
    SYMBOL_RIGHT_PARENTHESIS,      // )
    SYMBOL_LEFT_BRACE,      // {
    SYMBOL_RIGHT_BRACE,      // }
    SYMBOL_LEFT_BRACKET,    // [
    SYMBOL_RIGHT_BRACKET,    // ]
    SYMBOL_SEMICOLON,
    SYMBOL_COMMA,
    SYMBOL_DOT,
    SYMBOL_COLON,
    SYMBOL_QUESTION_MARK,
    
    // Special Tokens
    SPECIAL_END_OF_FILE,         // End of file
    SPECIAL_UNKNOWN

}
