package ch.zhaw.it.pm4.javer.compiler.parser;

import ch.zhaw.it.pm4.javer.compiler.ast.nodes.CompilationUnit;
import ch.zhaw.it.pm4.javer.compiler.ast.nodes.caseLabel.CaseLabelAstNode;
import ch.zhaw.it.pm4.javer.compiler.ast.nodes.caseLabel.EnumCaseLabel;
import ch.zhaw.it.pm4.javer.compiler.ast.nodes.caseLabel.LiteralCaseLabel;
import ch.zhaw.it.pm4.javer.compiler.ast.nodes.declaration.*;
import ch.zhaw.it.pm4.javer.compiler.ast.nodes.expression.*;
import ch.zhaw.it.pm4.javer.compiler.ast.nodes.statement.*;
import ch.zhaw.it.pm4.javer.compiler.ast.nodes.type.*;
import ch.zhaw.it.pm4.javer.compiler.lexer.Token;
import ch.zhaw.it.pm4.javer.compiler.lexer.TokenType;
import ch.zhaw.it.pm4.javer.compiler.misc.SourceLocation;
import ch.zhaw.it.pm4.javer.compiler.misc.diagnostics.DiagnosticBag;

import java.util.ArrayList;
import java.util.List;

/**
 * A Recursive Descent Parser for the Javer programming language.
 * <p>
 * This parser is responsible for taking a linear sequence of {@link Token}s
 * generated by the Lexer and organizing them into a Concrete Syntax Tree (CST).
 * It strictly follows the LL(1) Javer formal grammar.
 * <p>
 * To support the educational goals of the language, this parser implements
 * graceful error recovery. Instead of throwing exceptions upon encountering
 * syntax errors, it records them in the {@link DiagnosticBag} and attempts
 * to continue parsing to find subsequent errors.
 */
public class Parser {

    private final List<Token> tokens;
    private final DiagnosticBag diagnosticBag;
    private int currentPosition = 0;

    /**
     * Constructs a new Parser instance.
     *
     * @param tokens The complete list of tokens generated by the Lexer.
     *               Must end with an EOF (End of File) token.
     *               errors gracefully without halting the compiler pipeline.
     */
    public Parser(List<Token> tokens, DiagnosticBag diagnosticBag) {
        this.tokens = tokens;
        this.diagnosticBag = diagnosticBag;
    }

    /**
     * Starts the parsing process.
     * <p>
     * This method acts as the entry point for the compiler pipeline and matches
     * the root {@code compilationUnit} grammar rule. It iterates through the
     * token stream and constructs the highest level of the syntax tree.
     *
     * @return The root node ({@link CompilationUnit}) of the resulting
     * Concrete Syntax Tree (CST).
     */
    public CompilationUnit parse() {
        return parseCompilationUnit();
    }

    private Token currentToken() {
        return peek(0);
    }

    private Token lookahead() {
        return peek(1);
    }

    private Token peek(int offset) {
        int i = currentPosition + offset;
        if (i < 0) i = 0;
        if (i >= tokens.size()) {
            // this could be much better done
            if (tokens.isEmpty()) return new Token(TokenType.SPECIAL_END_OF_FILE, "", new SourceLocation(0, 0, 0));
            else return tokens.getLast();
        }
        return tokens.get(i);
    }

    private boolean matchCurrentToken(TokenType tokenType) {
        return currentToken().getTokenType() == tokenType;
    }

    private boolean matchNextToken(TokenType tokenType) {
        return lookahead().getTokenType() == tokenType;
    }

    private boolean matchAnyCurrentToken(TokenType... tokenTypes) {
        for (TokenType tokenType : tokenTypes) {
            if (matchCurrentToken(tokenType)) return true;
        }
        return false;
    }

    private boolean matchAnyNextToken(TokenType... tokenTypes) {
        TokenType lookAheadTokenType = lookahead().getTokenType();
        for (TokenType tokenType : tokenTypes) {
            if (lookAheadTokenType == tokenType) return true;
        }
        return false;
    }

    private Token consumeToken() {
        Token t = currentToken();
        if(currentPosition < tokens.size()) currentPosition++;
        return t;
    }

    private boolean expectTokenType(TokenType tokenType) {
        if(currentToken().getTokenType() == tokenType) return true;
        else {
            reportExpectedToken(tokenType);
            return false;
        }
    }

    // TODO
    private void reportExpectedToken(TokenType tokenType) {
    }

    // ============================================================
    // Top-Level
    // ============================================================

    private CompilationUnit parseCompilationUnit() {
        return new CompilationUnit(parseDeclarations());
    }

    private DeclarationAstNode parseDeclaration() {
        if(matchCurrentToken(TokenType.TYPE_ENUM)) return parseEnumDeclaration();
        if(matchCurrentToken(TokenType.TYPE_STRUCT)) return parseStructDeclaration();
        if(matchCurrentToken(TokenType.KEYWORD_FUNCTION)) return parseFunctionDeclaration();
        return null;
    }

    private EnumDeclaration parseEnumDeclaration() {
        expectTokenType(TokenType.TYPE_ENUM);



        return new EnumDeclaration("", new ArrayList<>());
    }

    private EnumItem parseEnumItem() {
        return EnumItem
                .builder("")
                .build();
    }

    private StructDeclaration parseStructDeclaration() {
        return new StructDeclaration("", new ArrayList<>());
    }

    private StructField parseStructField() {
        return new StructField(null, "");
    }

    private FunctionDeclaration parseFunctionDeclaration() {
        return new FunctionDeclaration(null, "", new ArrayList<>(), null);
    }

    private FunctionParameter parseFunctionParameter() {
        return new FunctionParameter("", null);
    }


    // ============================================================
    // Types
    // ============================================================

    private TypeAstNode parseType() {
        return new VoidType();
    }

    private TypeAstNode parseReturnType() {
        return new VoidType();
    }

    private TypeAstNode parseTypeHead() {
        return new PrimitiveType(PrimitiveTypeKind.INT);
    }

    private PrimitiveType parsePrimitiveType() {
        return new PrimitiveType(PrimitiveTypeKind.INT);
    }

    private NamedType parseNamedType() {
        return new NamedType(NameTypeKind.ENUM, "");
    }

    private VoidType parseVoidType() {
        return new VoidType();
    }

    // TODO is this signature okay?
    private ArrayType wrapArrayDimensions(TypeAstNode baseType, int arrayDepth) {
        return new ArrayType(baseType);
    }


    // ============================================================
    // Statements / Blocks
    // ============================================================

    private BlockStatement parseBlock() {
        return new BlockStatement(new ArrayList<>());
    }

    private StatementAstNode parseStatement() {
        return switch (currentToken().getTokenType()) {
            case TokenType.KEYWORD_IF -> parseIfStatement();
            case TokenType.KEYWORD_WHILE -> parseWhileStatement();
            case TokenType.KEYWORD_DO -> parseDoWhileStatement();
            case TokenType.KEYWORD_FOR -> parseForStatement();
            case TokenType.KEYWORD_SWITCH -> parseSwitchStatement();
            case TokenType.KEYWORD_RETURN, TokenType.KEYWORD_BREAK, TokenType.KEYWORD_CONTINUE -> parseJumpStatement();
            case TokenType.KEYWORD_LET -> parseVarDeclarationStatement();
            default -> parseExpressionStatement();
        };
    }

    private IfStatement parseIfStatement() {
        return IfStatement.builder(null, null).build();
    }

    private WhileStatement parseWhileStatement() {
        return new WhileStatement(null, null);
    }

    private DoWhileStatement parseDoWhileStatement() {
        return new DoWhileStatement(null, null);
    }

    private ForStatement parseForStatement() {
        return ForStatement.builder(null).build();
    }

    private ForInit parseForInit() {
        return parseForInitVarDeclaration();
    }

    private ForInitVarDeclaration parseForInitVarDeclaration() {
        return new ForInitVarDeclaration(null);
    }

    private ForInitExpressionList parseForInitExpressionList() {
        return new ForInitExpressionList(null);
    }

    private SwitchStatement parseSwitchStatement() {
        return new SwitchStatement(null, new ArrayList<>());
    }

    private SwitchCase parseSwitchCase() {
        return new SwitchCase(false, new ArrayList<>(), null);
    }

    private StatementAstNode parseJumpStatement() {
        return switch (currentToken().getTokenType()) {
            case TokenType.KEYWORD_RETURN -> parseReturnStatement();
            case TokenType.KEYWORD_BREAK -> parseBreakStatement();
            case TokenType.KEYWORD_CONTINUE -> parseContinueStatement();
            default -> null;
        };
    }

    private BreakStatement parseBreakStatement() {
        return new BreakStatement();
    }

    private ContinueStatement parseContinueStatement() {
        return new ContinueStatement();
    }

    private ReturnStatement parseReturnStatement() {
        return ReturnStatement.builder(null).build();
    }

    private VarDeclarationStatement parseVarDeclarationStatement() {
        return VarDeclarationStatement.builder(null, "").build();
    }

    // nur falls du expression ';' als eigenen AST-Knoten ergänzst:
    private StatementAstNode parseExpressionStatement() {
        return null;
    }


    // ============================================================
    // Switch / Case Labels
    // ============================================================

    private LiteralCaseLabel parseLiteralCaseLabel() {
        return new LiteralCaseLabel(null);
    }

    private EnumCaseLabel parseEnumCaseLabel() {
        return new EnumCaseLabel("", "");
    }


    // ============================================================
    // Variable / Array Initializers
    // ============================================================

    private ArrayInitExpression parseArrayInitExpression() {
        return new ArrayInitExpression(new ArrayList<>());
    }

    private ExpressionAstNode parseVarInitializer() {
        return parseArrayInitExpression();
    }


// ============================================================
// Expression Lists
// ============================================================

    private List<ExpressionAstNode> parseExpressionList() {
        return null;
    }

    private List<ExpressionAstNode> parseOptionalExpressionList() {
        return null;
    }


// ============================================================
// Expressions (gemäss Präzedenz deiner Grammatik)
// ============================================================

    private ExpressionAstNode parseExpression() {
        return null;
    }

    private ExpressionAstNode parseAssignment() {
        return null;
    }

    private AssignOperator parseAssignOperator() {
        return null;
    }

    private ExpressionAstNode parseConditional() {
        return null;
    }

    private ExpressionAstNode parseLogicalOr() {
        return null;
    }

    private ExpressionAstNode parseLogicalAnd() {
        return null;
    }

    private ExpressionAstNode parseInclusiveOr() {
        return null;
    }

    private ExpressionAstNode parseExclusiveOr() {
        return null;
    }

    private ExpressionAstNode parseAndExpression() {
        return null;
    }

    private ExpressionAstNode parseEqualityExpression() {
        return null;
    }

    private ExpressionAstNode parseRelationalExpression() {
        return null;
    }

    private ExpressionAstNode parseShiftExpression() {
        return null;
    }

    private ExpressionAstNode parseAdditiveExpression() {
        return null;
    }

    private ExpressionAstNode parseMultiplicativeExpression() {
        return null;
    }

    private ExpressionAstNode parseUnaryExpression() {
        return null;
    }

    private ExpressionAstNode parsePostfixExpression() {
        return null;
    }

    private ExpressionAstNode parsePrimaryExpression() {
        return null;
    }


// ============================================================
// Postfix / Access / Call / New
// ============================================================

    private ExpressionAstNode parseCallExpression() {
        return null;
    }

    private ExpressionAstNode parseNameExpression() {
        return null;
    }

    private IndexExpression parseIndexExpression(ExpressionAstNode target) {
        return null;
    }

    private MemberAccessExpression parseMemberAccessExpression(ExpressionAstNode target) {
        return null;
    }

    private NewExpression parseNewExpression() {
        return null;
    }

    private List<ExpressionAstNode> parseNewArrayDimensions() {
        return null;
    }


// ============================================================
// Literals
// ============================================================

    private LiteralExpression<?> parseLiteralExpression() {
        return null;
    }

    private LiteralExpression<?> parseNumberLiteral() {
        return null;
    }

    private LiteralExpression<Boolean> parseBooleanLiteral() {
        return null;
    }

    private LiteralExpression<String> parseStringLiteral() {
        return null;
    }

    private LiteralExpression<Character> parseCharLiteral() {
        return new LiteralExpression<>(LiteralKind.CHAR, null);
    }

    private LiteralExpression<Void> parseNullLiteral() {
        return new LiteralExpression<>(LiteralKind.NULL, null);
    }


// ============================================================
// Operator Mapping Helpers
// ============================================================

    private BinaryExpressionKind toBinaryExpressionKind(Token token) {
        return switch (token.getTokenType()) {
            case TokenType.OPERATOR_PLUS -> BinaryExpressionKind.ADD;
            case TokenType.OPERATOR_MINUS -> BinaryExpressionKind.SUBTRACT;
            case TokenType.OPERATOR_MULTIPLY -> BinaryExpressionKind.MULTIPLY;
            case TokenType.OPERATOR_DIVIDE -> BinaryExpressionKind.DIVIDE;
            case TokenType.OPERATOR_MODULO -> BinaryExpressionKind.MODULO;
            case TokenType.OPERATOR_AND -> BinaryExpressionKind.AND;
            case TokenType.OPERATOR_OR -> BinaryExpressionKind.OR;
            case TokenType.OPERATOR_BITWISE_OR -> BinaryExpressionKind.BITWISE_OR;
            case TokenType.OPERATOR_BITWISE_AND -> BinaryExpressionKind.BITWISE_AND;
            case TokenType.OPERATOR_BITWISE_XOR -> BinaryExpressionKind.BITWISE_XOR;
            case TokenType.OPERATOR_EQUALS -> BinaryExpressionKind.EQUALS;
            case TokenType.OPERATOR_NOT_EQUALS -> BinaryExpressionKind.NOT_EQUALS;
            case TokenType.OPERATOR_LESS_THAN -> BinaryExpressionKind.LESS;
            case TokenType.OPERATOR_LESS_EQUAL -> BinaryExpressionKind.LESS_EQUALS;
            case TokenType.OPERATOR_GREATER_THAN -> BinaryExpressionKind.GREATER;
            case TokenType.OPERATOR_GREATER_EQUAL -> BinaryExpressionKind.GREATER_EQUALS;
            case TokenType.OPERATOR_BITSHIFT_LEFT -> BinaryExpressionKind.SHIFT_LEFT;
            case TokenType.OPERATOR_BITSHIFT_RIGHT -> BinaryExpressionKind.SHIFT_RIGHT;
            default -> BinaryExpressionKind.INVALID;
        };
    }

    private UnaryExpressionKind toUnaryExpressionKind(Token token) {
        return switch (token.getTokenType()) {
            case TokenType.OPERATOR_PLUS -> UnaryExpressionKind.PLUS;
            case TokenType.OPERATOR_MINUS -> UnaryExpressionKind.MINUS;
            case TokenType.OPERATOR_LOGICAL_NOT -> UnaryExpressionKind.LOGICAL_NOT;
            case TokenType.OPERATOR_BITWISE_NOT -> UnaryExpressionKind.BITWISE_NOT;
            case TokenType.OPERATOR_INCREMENT -> UnaryExpressionKind.PRE_INCREMENT;
            case TokenType.OPERATOR_DECREMENT -> UnaryExpressionKind.PRE_DECREMENT;
            default -> UnaryExpressionKind.INVALID;
        };
    }

    private PostfixOperationKind toPostfixOperationKind(Token token) {
        return switch (token.getTokenType()) {
            case TokenType.OPERATOR_INCREMENT -> PostfixOperationKind.INCREMENT;
            case TokenType.OPERATOR_DECREMENT -> PostfixOperationKind.DECREMENT;
            default -> PostfixOperationKind.INVALID;
        };
    }

    private AssignOperator toAssignOperator(Token token) {
        return switch (token.getTokenType()) {
            case TokenType.OPERATOR_ASSIGN -> AssignOperator.ASSIGN;
            case TokenType.OPERATOR_PLUS_ASSIGN -> AssignOperator.ADD_ASSIGN;
            case TokenType.OPERATOR_MINUS_ASSIGN -> AssignOperator.SUB_ASSIGN;
            case TokenType.OPERATOR_MULTIPLY_ASSIGN -> AssignOperator.MUL_ASSIGN;
            case TokenType.OPERATOR_DIVIDE_ASSIGN -> AssignOperator.DIV_ASSIGN;
            case TokenType.OPERATOR_MODULO_ASSIGN -> AssignOperator.MOD_ASSIGN;
            case TokenType.OPERATOR_BITWISE_OR_ASSIGN -> AssignOperator.BITWISE_OR_ASSIGN;
            case TokenType.OPERATOR_BITWISE_AND_ASSIGN -> AssignOperator.BITWISE_AND_ASSIGN;
            case TokenType.OPERATOR_BITWISE_XOR_ASSIGN -> AssignOperator.BITWISE_XOR_ASSIGN;
            case TokenType.OPERATOR_BITSHIFT_LEFT_ASSIGN -> AssignOperator.LEFT_SHIFT_ASSIGN;
            case TokenType.OPERATOR_BITSHIFT_RIGHT_ASSIGN -> AssignOperator.RIGHT_SHIFT_ASSIGN;
            default -> AssignOperator.INVALID;
        };
    }

    private PrimitiveTypeKind toPrimitiveTypeKind(Token token) {
        return switch (token.getTokenType()) {
            case TokenType.TYPE_INTEGER -> PrimitiveTypeKind.INT;
            case TokenType.TYPE_DOUBLE -> PrimitiveTypeKind.DOUBLE;
            case TokenType.TYPE_BOOLEAN -> PrimitiveTypeKind.BOOL;
            case TokenType.TYPE_STRING -> PrimitiveTypeKind.STRING;
            case TokenType.TYPE_CHARACTER -> PrimitiveTypeKind.CHAR;
            default -> PrimitiveTypeKind.INVALID;
        };
    }

    private NameTypeKind toNameTypeKind(Token token) {
        return switch (token.getTokenType()) {
            case TokenType.TYPE_STRUCT -> NameTypeKind.STRUCT;
            case TokenType.TYPE_ENUM -> NameTypeKind.ENUM;
            default -> NameTypeKind.INVALID;
        };
    }


// ============================================================
// Optional / Repetition Helpers
// ============================================================

    private List<DeclarationAstNode> parseDeclarations() {
        ArrayList<DeclarationAstNode> declarations = new ArrayList<>();
        while (!matchCurrentToken(TokenType.SPECIAL_END_OF_FILE)) {
            if (isDeclarationStart(currentToken())) {
                declarations.add(parseDeclaration());
            } else {
                // error
                break;
            }
        }
        return declarations;
    }

    private List<EnumItem> parseEnumItems() {
        return new ArrayList<>();
    }

    private List<StructField> parseStructFields() {
        return new ArrayList<>();
    }

    private List<FunctionParameter> parseFunctionParameters() {
        return new ArrayList<>();
    }

    private List<SwitchCase> parseSwitchCases() {
        return new ArrayList<>();
    }

    private List<CaseLabelAstNode> parseCaseLabels() {
        return new ArrayList<>();
    }


// ============================================================
// Token / Recovery Helpers
// ============================================================

    private boolean isDeclarationStart(Token token) {
        TokenType type = token.getTokenType();
        return switch (type) {
            case TokenType.TYPE_ENUM, TokenType.TYPE_STRUCT, TokenType.KEYWORD_FUNCTION -> true;
            default -> false;
        };
    }

    private boolean isStatementStart(Token token) {
        return false;
    }

    private boolean isTypeStart(Token token) {
        return false;
    }

    private boolean isLiteralStart(Token token) {
        return false;
    }

    private boolean isAssignmentOperator(Token token) {
        return false;
    }

    private boolean isUnaryOperator(Token token) {
        return false;
    }

    private boolean isPostfixOperator(Token token) {
        return false;
    }


}
