package ch.zhaw.it.pm4.javer.application;

import ch.zhaw.it.pm4.misc.JaverLogger;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.CheckBox;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;
import javafx.scene.layout.VBox;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.List;

/**
 * Controller for the main GUI. It owns the source input, process output panes,
 * status log pane, compiler/VM process runners, and runtime files used to pass
 * source and bytecode between tools.
 */
public class GuiController {

    private static final String CONSOLE_INPUT_FILE_NAME = "console-input.javer";
    private static final String VM_INPUT_FILE_NAME = "vm-input.jbc";
    private static final String BYTECODE_FILE_EXTENSION = ".jbc";
    private static final List<String> TOOL_JAVA_OPTIONS = List.of(
            "-Dfile.encoding=UTF-8",
            "-Dstdout.encoding=UTF-8",
            "-Dstderr.encoding=UTF-8"
    );

    // Packaged release layout inside Application app image
    private static final Path RELEASE_COMPILER_EXE = Path.of("app", "tools", "Compiler", "javer-compiler.exe");
    private static final Path RELEASE_VM_EXE = Path.of("app", "tools", "VM", "javer-vm.exe");

    private final Path runtimeDirectory = resolveRuntimeDirectory();
    private final Path consoleInputFile = runtimeDirectory.resolve(CONSOLE_INPUT_FILE_NAME);
    private final Path vmInputFile = runtimeDirectory.resolve(VM_INPUT_FILE_NAME);

    private ManagedProcessRunner compilerRunner;
    private ManagedProcessRunner vmRunner;

    @FXML
    private Button runVMButton;

    @FXML
    private Button stopCompilerButton;

    @FXML
    private Button stopVMButton;

    @FXML
    private Button runCompilerAndVMButton;

    @FXML
    private TextArea compilerOutput;

    @FXML
    private TextArea virtualMachineOutput;

    @FXML
    private TextArea consoleInput;

    @FXML
    private Button runCompilerButton;

    @FXML
    private TextArea statusOutput;

    @FXML
    private CheckBox expertModeOption;

    @FXML
    private VBox compilerOptionsBox;

    @FXML
    private VBox vmOptionsBox;

    @FXML
    private CheckBox compilerDumpLexerOption;

    @FXML
    private CheckBox compilerDumpAstOption;

    @FXML
    private CheckBox compilerDumpSymbolTableOption;

    @FXML
    private CheckBox compilerLoggingOption;

    @FXML
    private TextField vmStackSizeOption;

    @FXML
    private CheckBox vmDumpOnErrorOption;

    @FXML
    private TextField vmAdditionalArguments;

    /**
     * Creates the controller instance used by the FXML loader.
     */
    public GuiController() {
    }

    /**
     * Initializes process runners, logging integration, and initial button
     * state after FXML injection has completed.
     */
    @FXML
    public void initialize() {
        GuiLogAppender.setConsumer(this::appendStatus);

        JaverLogger.info("GUI initialized");
        JaverLogger.info("Working directory: " + Path.of("").toAbsolutePath().normalize());
        JaverLogger.info("Runtime file directory: " + runtimeDirectory);

        compilerRunner = new ManagedProcessRunner(
                "Compiler",
                this::appendCompilerOutput,
                this::appendCompilerOutput,
                this::updateCompilerButtons
        );

        vmRunner = new ManagedProcessRunner(
                "VM",
                this::appendVMOutput,
                this::appendVMOutput,
                this::updateVMButtons
        );

        updateCompilerButtons(false);
        updateVMButtons(false);
        bindExpertMode();
    }

    /**
     * Writes the editor contents to disk and starts only the compiler process.
     */
    @FXML
    protected void onRunCompilerClick() {
        if (compilerRunner.isRunning()) {
            return;
        }

        compilerOutput.clear();

        String inputPath = writeInputToFile(consoleInput.getText());
        if (inputPath == null || !deleteFileIfExists(vmInputFile, "VM input file")) {
            return;
        }

        List<String> command = buildCompilerCommand(inputPath);
        if (command == null) {
            return;
        }

        logCommand("Compiler", command);

        if (compilerRunner.start(command).isEmpty()) {
            JaverLogger.warning("Compiler is already running.");
        }
    }

    /**
     * Starts only the VM process with the latest generated bytecode file.
     */
    @FXML
    protected void onRunVMClick() {
        if (vmRunner.isRunning()) {
            return;
        }

        virtualMachineOutput.clear();

        List<String> command = buildVmCommand();
        if (command == null) {
            return;
        }

        logCommand("VM", command);

        if (vmRunner.start(command).isEmpty()) {
            JaverLogger.warning("VM is already running.");
        }
    }

    /**
     * Requests termination of the VM process.
     */
    @FXML
    public void onStopVMClick() {
        vmRunner.stop();
    }

    /**
     * Requests termination of the compiler process.
     */
    @FXML
    public void onStopCompilerClick() {
        compilerRunner.stop();
    }

    /**
     * Stops managed processes, removes runtime source/bytecode files, and
     * detaches the GUI log appender.
     */
    public void shutdown() {
        JaverLogger.info("Application shutdown started.");

        if (compilerRunner != null) {
            compilerRunner.stopAndWait();
        }
        if (vmRunner != null) {
            vmRunner.stopAndWait();
        }

        deleteRuntimeFileIfExists(consoleInputFile, "source input file");
        deleteRuntimeFileIfExists(vmInputFile, "VM input file");
        GuiLogAppender.clearConsumer();
    }

    /**
     * Runs compiler and VM as a sequence. The VM starts only after the compiler
     * has completed successfully and produced a non-empty bytecode file.
     */
    @FXML
    public void onRunCompilerAndVMClick() {
        if (compilerRunner.isRunning() || vmRunner.isRunning()) {
            JaverLogger.warning("Compiler or VM is already running.");
            return;
        }

        compilerOutput.clear();
        virtualMachineOutput.clear();

        String inputPath = writeInputToFile(consoleInput.getText());
        if (inputPath == null || !deleteFileIfExists(vmInputFile, "VM input file")) {
            return;
        }

        List<String> compilerCommand = buildCompilerCommand(inputPath);
        List<String> vmCommand = buildVmCommand();

        if (compilerCommand == null || vmCommand == null) {
            return;
        }

        logCommand("Compiler", compilerCommand);

        var compilerRun = compilerRunner.start(compilerCommand);
        if (compilerRun.isEmpty()) {
            JaverLogger.warning("Compiler is already running.");
            return;
        }

        compilerRun.get().thenAccept(result -> startVmAfterSuccessfulCompilation(result, vmCommand));
    }

    private List<String> buildCompilerCommand(String inputPath) {
        String compilerOutputPath = bytecodeOutputBasePath(vmInputFile).toAbsolutePath().toString();

        List<String> command = new ArrayList<>();
        Path compilerExe = resolveReleaseExecutable(RELEASE_COMPILER_EXE, "Compiler");
        if (compilerExe != null) {
            command.add(compilerExe.toString());
        } else {
            Path compilerJar = resolveJarFromProperty("javer.compiler.jar");
            if (compilerJar == null) {
                JaverLogger.error("Compiler executable and IDE jar are both unavailable.");
                return null;
            }
            addJavaJarCommand(command, compilerJar);
        }

        command.add("--in-file");
        command.add(inputPath);
        command.add("--out-file");
        command.add(compilerOutputPath);
        addCompilerOptions(command);

        return command;
    }

    private void addCompilerOptions(List<String> command) {
        if (!expertModeOption.isSelected()) {
            return;
        }

        if (compilerDumpLexerOption.isSelected()) {
            command.add("--dump-lexer");
        }
        if (compilerDumpAstOption.isSelected()) {
            command.add("--dump-ast");
        }
        if (compilerDumpSymbolTableOption.isSelected()) {
            command.add("--dump-symboltable");
        }
        if (compilerLoggingOption.isSelected()) {
            command.add("--logging");
        }
    }

    private Path bytecodeOutputBasePath(Path bytecodeFile) {
        String fileName = bytecodeFile.getFileName().toString();
        if (!fileName.endsWith(BYTECODE_FILE_EXTENSION)) {
            return bytecodeFile;
        }

        String baseName = fileName.substring(0, fileName.length() - BYTECODE_FILE_EXTENSION.length());
        return bytecodeFile.resolveSibling(baseName);
    }

    private List<String> buildVmCommand() {
        List<String> command = new ArrayList<>();
        Path vmExe = resolveReleaseExecutable(RELEASE_VM_EXE, "VM");
        if (vmExe != null) {
            command.add(vmExe.toString());
        } else {
            Path vmJar = resolveJarFromProperty("javer.vm.jar");
            if (vmJar == null) {
                JaverLogger.error("VM executable and IDE jar are both unavailable.");
                return null;
            }
            addJavaJarCommand(command, vmJar);
        }

        if (expertModeOption.isSelected()) {
            addVmOptions(command);
        }
        command.add(vmInputFile.toAbsolutePath().toString());

        return command;
    }

    private void addVmOptions(List<String> command) {
        String stackSize = vmStackSizeOption.getText();
        if (stackSize != null && !stackSize.isBlank()) {
            command.add("--stack-size");
            command.add(stackSize.trim());
        }

        if (vmDumpOnErrorOption.isSelected()) {
            command.add("--dump-on-error");
        }

        command.addAll(parseAdditionalArguments(vmAdditionalArguments.getText()));
    }

    private void addJavaJarCommand(List<String> command, Path jarPath) {
        command.add("java");
        command.addAll(TOOL_JAVA_OPTIONS);
        command.add("-jar");
        command.add(jarPath.toString());
    }

    private void bindExpertMode() {
        compilerOptionsBox.visibleProperty().bind(expertModeOption.selectedProperty());
        compilerOptionsBox.managedProperty().bind(expertModeOption.selectedProperty());
        vmOptionsBox.visibleProperty().bind(expertModeOption.selectedProperty());
        vmOptionsBox.managedProperty().bind(expertModeOption.selectedProperty());
    }

    private List<String> parseAdditionalArguments(String arguments) {
        List<String> parsedArguments = new ArrayList<>();
        if (arguments == null || arguments.isBlank()) {
            return parsedArguments;
        }

        StringBuilder currentArgument = new StringBuilder();
        boolean quoted = false;

        for (int i = 0; i < arguments.length(); i++) {
            char character = arguments.charAt(i);

            if (character == '"') {
                quoted = !quoted;
                continue;
            }

            if (Character.isWhitespace(character) && !quoted) {
                addArgumentIfPresent(parsedArguments, currentArgument);
                continue;
            }

            currentArgument.append(character);
        }

        if (quoted) {
            JaverLogger.warning("VM arguments contain an unclosed quote; using the remaining text as one argument.");
        }

        addArgumentIfPresent(parsedArguments, currentArgument);
        return parsedArguments;
    }

    private void addArgumentIfPresent(List<String> arguments, StringBuilder argument) {
        if (!argument.isEmpty()) {
            arguments.add(argument.toString());
            argument.setLength(0);
        }
    }

    private void startVmAfterSuccessfulCompilation(
            ManagedProcessRunner.ProcessResult compilerResult,
            List<String> vmCommand
    ) {
        if (!compilerResult.isSuccess()) {
            JaverLogger.warning("Compiler did not finish successfully. VM will not be started.");
            return;
        }

        if (!isBytecodeFileReady()) {
            JaverLogger.error("Compiler finished, but the VM input file is missing or empty: "
                    + vmInputFile.toAbsolutePath());
            return;
        }

        if (vmRunner.isRunning()) {
            JaverLogger.warning("VM is already running.");
            return;
        }

        logCommand("VM", vmCommand);
        if (vmRunner.start(vmCommand).isEmpty()) {
            JaverLogger.warning("VM is already running.");
        }
    }

    private boolean isBytecodeFileReady() {
        try {
            return Files.isRegularFile(vmInputFile) && Files.size(vmInputFile) > 0;
        } catch (IOException exception) {
            JaverLogger.error("Failed to inspect VM input file: " + exception.getMessage());
            return false;
        }
    }

    private String writeInputToFile(String input) {
        String content = input == null ? "" : input;

        try {
            Files.writeString(
                    consoleInputFile,
                    content,
                    StandardCharsets.UTF_8,
                    StandardOpenOption.CREATE,
                    StandardOpenOption.TRUNCATE_EXISTING
            );
            JaverLogger.info("Created source input file: " + consoleInputFile.toAbsolutePath());
            return consoleInputFile.toAbsolutePath().toString();
        } catch (IOException exception) {
            JaverLogger.error("Failed to write source input file: " + exception.getMessage());
            return null;
        }
    }

    private boolean deleteFileIfExists(Path path, String label) {
        try {
            Path parent = path.toAbsolutePath().getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
            if (Files.deleteIfExists(path)) {
                JaverLogger.info("Deleted previous " + label + ": " + path.toAbsolutePath());
            }
            return true;
        } catch (IOException e) {
            JaverLogger.error("Failed to delete previous " + label + ": " + e.getMessage());
            return false;
        }
    }

    private void deleteRuntimeFileIfExists(Path path, String label) {
        try {
            if (Files.deleteIfExists(path)) {
                JaverLogger.info("Deleted " + label + ": " + path.toAbsolutePath());
            }
        } catch (IOException e) {
            JaverLogger.warning("Failed to delete " + label + ": " + e.getMessage());
        }
    }

    private Path resolveReleaseExecutable(Path relativePath, String label) {
        Path path = runtimeDirectory.resolve(relativePath).toAbsolutePath().normalize();

        if (!Files.exists(path) || !Files.isRegularFile(path)) {
            JaverLogger.debug(label + " packaged executable not found at: " + path);
            return null;
        }

        JaverLogger.info("Resolved " + label + " executable to: " + path);
        return path;
    }

    private static Path resolveRuntimeDirectory() {
        Path workingDirectory = Path.of(System.getProperty("user.dir")).toAbsolutePath().normalize();
        Path codeLocation = getCodeLocation();
        Path packagedRoot = findPackagedAppRoot(codeLocation);
        if (packagedRoot != null) {
            return packagedRoot;
        }

        Path projectRoot = findProjectRoot(workingDirectory);
        if (projectRoot != null) {
            return projectRoot;
        }

        projectRoot = findProjectRoot(codeLocation);
        if (projectRoot != null) {
            return projectRoot;
        }

        return workingDirectory;
    }

    private static Path getCodeLocation() {
        try {
            return Path.of(GuiController.class.getProtectionDomain()
                    .getCodeSource()
                    .getLocation()
                    .toURI()).toAbsolutePath().normalize();
        } catch (Exception exception) {
            return Path.of(System.getProperty("user.dir")).toAbsolutePath().normalize();
        }
    }

    private static Path findPackagedAppRoot(Path start) {
        Path path = Files.isRegularFile(start) ? start.getParent() : start;
        while (path != null) {
            Path fileName = path.getFileName();
            if (fileName != null
                    && "app".equalsIgnoreCase(fileName.toString())
                    && Files.isDirectory(path.resolve("tools"))) {
                return path.getParent();
            }
            path = path.getParent();
        }
        return null;
    }

    private static Path findProjectRoot(Path start) {
        Path path = Files.isRegularFile(start) ? start.getParent() : start;
        while (path != null) {
            if (Files.isRegularFile(path.resolve("pom.xml"))
                    && Files.isDirectory(path.resolve("Application"))
                    && Files.isDirectory(path.resolve("Compiler"))
                    && Files.isDirectory(path.resolve("VM"))) {
                return path;
            }
            path = path.getParent();
        }
        return null;
    }

    private Path resolveJarFromProperty(String propertyName) {
        String value = System.getProperty(propertyName);
        if (value == null || value.isBlank()) {
            JaverLogger.error("Missing system property: " + propertyName);
            JaverLogger.error("Please ensure JarConfigLoader.loadConfiguration() is called at startup or set the property manually.");
            return null;
        }

        Path path = Path.of(value).toAbsolutePath().normalize();
        if (!Files.exists(path) || !Files.isRegularFile(path)) {
            JaverLogger.error("Configured jar does not exist: " + path);
            JaverLogger.error("Make sure the jar file is present at the expected location.");
            JaverLogger.error("Property '" + propertyName + "' is set to: " + value);
            return null;
        }

        JaverLogger.info("Resolved " + propertyName + " to: " + path.toAbsolutePath());
        return path;
    }

    private void logCommand(String processName, List<String> command) {
        JaverLogger.info("Starting " + processName + " with command:");
        for (String part : command) {
            JaverLogger.info("  " + part);
        }
    }

    private void updateCompilerButtons(boolean running) {
        Platform.runLater(() -> {
            runCompilerButton.setDisable(running);
            stopCompilerButton.setDisable(!running);
            updateRunCompilerAndVMButtonState();
        });
    }

    private void updateVMButtons(boolean running) {
        Platform.runLater(() -> {
            runVMButton.setDisable(running);
            stopVMButton.setDisable(!running);
            updateRunCompilerAndVMButtonState();
        });
    }

    private void updateRunCompilerAndVMButtonState() {
        runCompilerAndVMButton.setDisable(isRunnerRunning(compilerRunner) || isRunnerRunning(vmRunner));
    }

    private boolean isRunnerRunning(ManagedProcessRunner runner) {
        return runner != null && runner.isRunning();
    }

    private void appendCompilerOutput(String text) {
        Platform.runLater(() -> compilerOutput.appendText(text));
    }

    private void appendVMOutput(String text) {
        Platform.runLater(() -> virtualMachineOutput.appendText(text));
    }

    private void appendStatus(String text) {
        Platform.runLater(() -> {
            statusOutput.appendText(text);
            statusOutput.setScrollTop(Double.MAX_VALUE);
        });
    }
}
