package ch.zhaw.it.pm4.javer.compiler;

public enum CompilationPhase {
    COMPILER_SETUP, ARGUMENT_PARSING, LEXING, PARSING, SYMBOL_TABLE_CREATION, NAME_RESOLUTION, TYPE_CHECKING, SEMANTIC_ANALYSIS, CODE_GENERATION, DONE
}
