package ch.zhaw.it.pm4.javer.compiler;

public enum CompilationPhase {
    ARGUMENT_PARSING, COMPILER_SETUP, LEXING, PARSING, SYMBOL_TABLE_CREATION, NAME_RESOLUTION, TYPE_CHECKING, SEMANTIC_ANALYSIS, CODE_GENERATION, DONE
}
